version: '3.7'
services:
  playwright:
    image: ${PLAYWRIGHT_IMAGE_NAME}
    volumes:
      - ./playwright.config.ts:/usr/src/app/playwright.config.ts:ro
      - ./tests:/usr/src/app/tests
      - ./pages:/usr/src/app/pages
      - playwright-report:/usr/src/app/allure-report
      - playwright-result:/usr/src/app/allure-results
    networks:
      - proxy
    labels:
      - traefik.frontend.rule=Host:${CI_COMMIT_REF_NAME}.playwright.tpsg.etpgpb.ru
      - traefik.docker.network=proxy
      - traefik.port=9323
volumes:
   playwright-result: {}
   playwright-report: {}
networks:
  proxy:
    external: true
