version: '3.7'
services:
  playwright:
    image: ${PLAYWRIGHT_IMAGE_NAME}
    volumes:
      - ./configs:/usr/src/app/configs
      - ./tests:/usr/src/app/tests
      - ./pages:/usr/src/app/pages
      - ./utilites:/usr/src/app/utilites
      - ./data:/usr/src/app/data
      - ./.auth:/usr/src/app/.auth:rw
      - playwright-report:/usr/src/app/allure-report
      - playwright-result:/usr/src/app/allure-results
    networks:
      - proxy
    labels:
      - traefik.frontend.rule=Host:${CI_COMMIT_REF_NAME}.playwright.tpsg.etpgpb.ru
      - traefik.docker.network=proxy
      - traefik.port=9323
    environment:
      BASE_URL: ${BASE_URL}
    extra_hosts:
    - "${URL_NAME}: 10.8.1.23"
volumes:
   playwright-result: {}
   playwright-report: {}
networks:
  proxy:
    external: true
